### ISSUE TITLE
Cannot receive any messges

### ISSUE THREAD

**Issue by tofuSCHNITZEL** [grimmpp/home-assistant-eltako#136]
Hi,
I have connected the FAM14 via usb and have the following USB device selection:
![image](https://github.com/user-attachments/assets/4a5b4375-ffe2-4a35-89c7-405f500ba99c)

but no matter what I select I can never see any "last message received" or any telegrams in the logs...
if I connect the FAM to my PC I can see a lot of chatter on the serial console:
![image](https://github.com/user-attachments/assets/c1ee6ac8-82ab-415e-9eb5-9c9695c4daf4)

here what I can see in the logs:
```
2024-11-13 17:51:12.441 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity sensor.eltako_gw1_ff_e3_7e_00_received_messages_per_session for domain sensor with platform eltako
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 599, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 831, in _async_add_entity
    unit_of_measurement=entity.unit_of_measurement,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 523, in unit_of_measurement
    if self._is_valid_suggested_unit(suggested_unit_of_measurement):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 385, in _is_valid_suggested_unit
    raise ValueError(
ValueError: Entity <class 'custom_components.eltako.sensor.GatewayReceivedMessagesInActiveSession'> suggest an incorrect unit of measurement: Messages.
2024-11-13 17:51:12.658 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration eltako with title: Eltako and entry_id: 01JCK6Z92KK1JCA6C7QPS1SG5H, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
Stack (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2318, in async_forward_entry_setup
    _report_non_awaited_platform_forwards(entry, "async_forward_entry_setup")
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1194, in _report_non_awaited_platform_forwards
    report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 156, in report
    _LOGGER.warning(msg, stack_info=True)
```

any idea?

**Comment by tofuSCHNITZEL** [comment]
Update - it just started working... maybe it needed to "sit" for a bit...
But when switching to fgw14usb and plugging in the FGW14USB I can't seem to get it to receive messages
![image](https://github.com/user-attachments/assets/e8094a12-508f-4e9b-95a5-7d2dd1b8262d)
![image](https://github.com/user-attachments/assets/2ee26ec0-5aeb-404d-bf4d-2b7decda5141)

**Comment by grimmpp** [comment]
Hello @tofuSCHNITZEL,

posted errors above are most probably unrelated to your issue and are solved for newer versions. Changing between FAM14 and FGW14-USB should require no changes except the device type in the config. 

Unfortunately, you need to properly restart HA. Quick restart is not enough.

**Comment by grimmpp** [comment]
The errors shown in this 2024 report have been removed in the current integration: the invalid gateway message-counter unit is fixed and the deprecated entry-forwarding API has been replaced. The current gateway/entity regression tests cover these paths. Closing this obsolete report.
