### ISSUE TITLE
high processor load (100%) after activating the device

### ISSUE THREAD

**Issue by stixif** [grimmpp/home-assistant-eltako#138]
after activating the device, the CPU load increases to 100%

it is connected via an FGB14-USB

I have 165 devices in use
and therefore also some entities

is it possible to improve performance here?

what would be the best approach to get something out of this

**Comment by stixif** [comment]
i reduced to 5 devices in the config for eltako
now the cpu load is on 37% and i can work...

is this my problem?

Logger: homeassistant.components.sensor
Quelle: helpers/entity_platform.py:608
Integration: Sensor (Dokumentation, Probleme)
Erstmals aufgetreten: 15:47:21 (1 Vorkommnisse)
Zuletzt protokolliert: 15:47:21

Error adding entity sensor.eltako_gw1_00_00_00_15_received_messages_per_session for domain sensor with platform eltako
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 608, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 840, in _async_add_entity
    unit_of_measurement=entity.unit_of_measurement,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 523, in unit_of_measurement
    if self._is_valid_suggested_unit(suggested_unit_of_measurement):
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 385, in _is_valid_suggested_unit
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Entity <class 'custom_components.eltako.sensor.GatewayReceivedMessagesInActiveSession'> suggest an incorrect unit of measurement: Messages.

**Comment by grimmpp** [comment]
There should be actually only load on the system if you send really many telegram constantly. I've made the experience that Eltako Bus is much slower than my HA device. 
I experienced more difficulties with some HA updates which had background processes causing load. Are you running the integration for longer?

**Comment by stixif** [comment]
no.. is a new installation of HA!
all works well.. (3-4% CPU Load)
but if i activate the Eltako integration with all devices (100% CPU Load)
with only 5 Devices it works with (30% CPU Load)

i make an update to the newest HA Verison today!

i have this error in the Log
`
Logger: homeassistant.components.sensor
Quelle: helpers/entity_platform.py:608
Integration: Sensor (Dokumentation, Probleme)
Erstmals aufgetreten: 13:31:31 (1 Vorkommnisse)
Zuletzt protokolliert: 13:31:31

Error adding entity sensor.eltako_gw1_00_00_00_15_received_messages_per_session for domain sensor with platform eltako
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 608, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 840, in _async_add_entity
    unit_of_measurement=entity.unit_of_measurement,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 523, in unit_of_measurement
    if self._is_valid_suggested_unit(suggested_unit_of_measurement):
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 385, in _is_valid_suggested_unit
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Entity <class 'custom_components.eltako.sensor.GatewayReceivedMessagesInActiveSession'> suggest an incorrect unit of measurement: Messages.
`

**Comment by stixif** [comment]
here a few errors, i got all the time...

2024-12-08 10:57:59.536 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity sensor.eltako_gw1_00_00_00_15_received_messages_per_session for domain sensor with platform eltako
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 608, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 840, in _async_add_entity
    unit_of_measurement=entity.unit_of_measurement,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 523, in unit_of_measurement
    if self._is_valid_suggested_unit(suggested_unit_of_measurement):
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 385, in _is_valid_suggested_unit
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Entity <class 'custom_components.eltako.sensor.GatewayReceivedMessagesInActiveSession'> suggest an incorrect unit of measurement: Messages.


2024-12-08 10:57:59.555 ERROR (MainThread) [homeassistant.components.cover] Error adding entity cover.eltako_gw1_00_00_00_31 for domain cover with platform eltako
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 608, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 927, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1383, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/eltako/device.py", line 102, in async_added_to_hass
    self.load_value_initially(latest_state)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/config/custom_components/eltako/cover.py", line 120, in load_value_initially
    raise e
  File "/config/custom_components/eltako/cover.py", line 88, in load_value_initially
    self._attr_current_cover_position = latest_state.attributes['current_position']
                                        ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'current_position'

**Comment by EnTeQuAk** [comment]
You could try to use https://github.com/grimmpp/home-assistant-eltako/pull/176, which is based on the latest 1.x and at least for me fixes a lot of instability in my home installation. Any feedback is very welcome 👼

**Comment by grimmpp** [comment]
This report targets Eltako 1.5.8/1.5.9 with Home Assistant Core 2024.12. The concrete errors reported alongside the CPU symptom (the invalid gateway message-counter unit and the cover restore KeyError) are fixed in the current 2.2.x code, and the relevant gateway, entity, simulation, plug-and-play, and cover regression tests pass. The original high-CPU behavior cannot be reproduced from the current code without the historical 165-device hardware setup. Closing this stale version-specific report; any new CPU regression should be reported with current-version profiling data.
