### ISSUE TITLE
KeyError: 'current_position' with FSB14

### ISSUE THREAD

**Issue by stixif** [grimmpp/home-assistant-eltako#139]
Hi,
i got this error for all Covers...

i use the newest version of HA 2024.12 and V1.5.8 of Eltako

i use FSB14
      cover:
      - id: 00-00-00-30           # address (HEX) 
        eep: G5-3F-7F             # Supported EEP telegrams: G5-3F-7F (FHEM A5-3F-7F)
        name: "Rollo_OG_WC"           # optional: display name
        sender:                   # virtual switch in Home Assistant.
          id: 02-00-00-30         # every sender needs it's own address which needs to be entered in PCT14 / actuator with function group 31 for FSB14.
          eep: H5-3F-7F
        device_class: shutter     # optional for showing the right icon and panels in Home Assistant
        time_closes: 24           # optional: The time it takes until the cover is completely closed (used for position calculation)
        time_opens: 18            # optional: The time it takes until the cover is completely opened (used for position calculation)

> 
2024-12-08 10:57:59.560 ERROR (MainThread) [homeassistant.components.cover] Error adding entity cover.eltako_gw1_00_00_00_32 for domain cover with platform eltako
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 608, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 927, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1383, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/eltako/device.py", line 102, in async_added_to_hass
    self.load_value_initially(latest_state)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/config/custom_components/eltako/cover.py", line 120, in load_value_initially
    raise e
  File "/config/custom_components/eltako/cover.py", line 88, in load_value_initially
    self._attr_current_cover_position = latest_state.attributes['current_position']
                                        ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'current_position'

**Comment by Meimax** [comment]
Hi, i got the same error.

**Comment by tgrimm1986-lgtm** [comment]
I have the Same issue. Any workaround known for that?

**Comment by skiddder** [comment]
I am currently installing my homeassistant initially and hit the same problem.

**Comment by Vankuche** [comment]
The exception message shows that the state of the shutter is "unknown". There is no state saved.
As workaround you can uncomment line 120 in cover.py (in version 1.5.9).
`#raise e`
```
        except Exception as e:
            self._attr_current_cover_position = None
            self._attr_current_cover_tilt_position = None
            self._attr_is_opening = None
            self._attr_is_closing = None
            self._attr_is_closed = None # means undefined state
            #raise e
```
So the control elements are available but the current state is unknown.

**Comment by Meimax** [comment]
I have only one cover from eltako, I just hard-coded the remote commands for the opening and closing.

```python
def open_cover(self, **kwargs: Any) -> None:
        data = RPSMessage(AddressExpression(b'\xFE\xFA\x9B\x95'),0x30,b'\x10', False)
        self.send_message(data)
        time.sleep(1)
        data = RPSMessage(AddressExpression(b'\xFE\xFA\x9B\x95'),0x20,b'\x00', False)
        self.send_message(data)
        return
```

It doesn't show any state, but in my case it's good enough.

**Comment by grimmpp** [comment]
Bug with no initial position for covers is fixed in:
https://github.com/grimmpp/home-assistant-eltako/releases/tag/v1.5.10-bugfix-covers
