### ISSUE TITLE
Repeating errors after  update to Core 2024.12.2

### ISSUE THREAD

**Issue by cypher0815** [grimmpp/home-assistant-eltako#143]
2024-12-11 19:23:40.689 ERROR (SyncWorker_28) [homeassistant.util.logging] Exception in _message_received_callback when dispatching 'eltako.gw_00-00-80-00.receive_message': (<EltakoWrapped4BS from 00-00-00-67, status 30, data 00-8C-78-0F>,)
Traceback (most recent call last):
  File "/config/custom_components/eltako/device.py", line 168, in _message_received_callback
    self.value_changed(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/config/custom_components/eltako/climate.py", line 325, in value_changed
    self.change_temperature_values(msg)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/config/custom_components/eltako/climate.py", line 353, in change_temperature_values
    if decoded.mode == A5_10_06.Heater_Mode.OFF:
                       ^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'A5_10_06' has no attribute 'Heater_Mode'. Did you mean: 'HeaterMode'?

**Comment by cypher0815** [comment]
Next repeating error:
2024-12-11 19:38:40.958 ERROR (MainThread) [eltako] 'bool' object has no attribute 'code'
Traceback (most recent call last):
  File "/config/custom_components/eltako/climate.py", line 192, in _wrapped_update
    await self._async_send_command(self._actuator_mode, self.target_temperature)
  File "/config/custom_components/eltako/climate.py", line 247, in _async_send_command
    self._send_command(mode, target_temp)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eltako/climate.py", line 254, in _send_command
    msg = A5_10_06(mode, target_temp, self.current_temperature, self.hvac_action == HVACAction.IDLE).encode_message(address)
  File "/usr/local/lib/python3.13/site-packages/eltakobus/eep.py", line 736, in encode_message
    data[3] = self.priority.code
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'code'

**Comment by grimmpp** [comment]
Obsolete for v2.2.1: the old climate API/attribute usage described here has been removed. Current climate entities use the current Home Assistant ClimateEntityFeature and EEP enum APIs; covered by the climate tests.
